[workspace]
resolver = "2"
members = [
    "dom",
    "malloc_size_of",
    "rustfmt.toml",
    "selectors",
    "servo_arc",
    "style",
    "style_derive",
    "style_static_prefs",
    "style_traits",
    "stylo_taffy",
    "to_shmem",
    "to_shmem_derive",
]
default-members = ["style"]
